controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  hi_controller:
    type: legged/hiController
  hi_cheater_controller:
    type: legged/LeggedCheaterController
  